### ISSUE TITLE
An option to always use `Global` user settings

### ISSUE THREAD

**Issue by usernamehw** [ryanraposo/codeui#13]
Probably > 95% of the time people will use the `Global` settings file, so I would like a setting to skip the scope choosing Quick Pick. (An just write to the `Global`).

**Comment by ryanraposo** [comment]
Actually in a previous state the status bar toggle we have now did exactly that, but i decided to just prompt for it with global already selected. Between the targeting mode and configuration scope, I believe targeting mode deserves a hard toggle. Because of how potentially complicated customizations can be, I want for qol reasons to keep the user cognizant of at least some of the impact variables on each action. There is a risk of wiping already existing setups as-is and I don't want it to be any higher.

I think many more users are setting up workspace details than you might think, but I do agree that it's probably not a volatile setting in a given session. I'll leave this issue up to get a better idea, I'm open to having my mind changed

**Comment by usernamehw** [comment]
I mean, it would be `false` by default...

```js
"codeui.alwaysUseGlobalSettings": false,
```

**Comment by ryanraposo** [comment]
I think i’ll bring back what it was, codeui.customizationScope with “alwaysAsk”, “global”, and “workspace”. 

alwaysAsk default. No toggle button

**Comment by ryanraposo** [comment]
Addressed in commit [6356767](https://github.com/ryanraposo/codeui/commit/63567676d1f53c55112aca72746c82c1f55d16dc)
